### ISSUE TITLE
Your server IP must be assigned to your forum user.

### ISSUE THREAD

**Issue by L2Separator** [Hl4p3x/L2jOrion_Interlude_C6#1]
Your server IP must be assigned to your forum user.

It's not cracked?

**Comment by nightw0lv** [comment]
https://github.com/Hl4p3x/L2jOrion_Interlude_C6/blob/master/L2jOrion_SourceCode/src/l2jorion/game/PSystem.java

**Comment by nightw0lv** [comment]
method check do it to return only true

**Comment by Hl4p3x** [comment]
Just remove PSytem and related config/database and compile again.

**Comment by K0uGou** [comment]
Source seems to be updated, but the datapack is no longer compatible with the source.

**Comment by hendbart** [comment]
Hi, can You tell me how to do it?
